### ISSUE TITLE
Support easily changing the endpoint of the openapi server

### ISSUE THREAD

**Issue by tristandruyen** [DocumindHQ/documind#3]
Great idea!

Just one issue, I don't really wanna give OpenAI access to my private documents. 
Luckily there is an easy solution. Just allow changing the URL of the API endpoint.
This would enable easily using alternative back-ends like [ollama](https://ollama.com/) that are API-compatible.
Probably just an environment variable would be enough.

**Comment by tkelley-eg** [comment]
I did some quick research and it looks as though you can set an environment variable for the baseURL (OPENAI_BASE_URL) since it's not explicitly passed.  There's support for other params as well.

https://github.com/openai/openai-node/blob/a92cc1dbc4ab3284c6654d69d5c39399a867f601/src/index.ts#L213

**Comment by danbarbarito** [comment]
It looks like the URL is currently hardcoded: https://github.com/DocumindHQ/documind/blob/171766d1783b4030e95be667af20b4523b087bb4/core/src/openAI.ts#L45

It would be really great if this can be set by an environment variable

**Comment by danbarbarito** [comment]
I believe this has been closed in c484fdd01de2a369827d0286381566e17b7b3254 🙏

**Comment by Tammilore** [comment]
Yes @danbarbarito , thanks.

Wanted to update on npm before closing.
